#!/bin/sh

# simple gitolite mirroring

# flush STDIN coming from git, because gitolite's own post-receive.mirrorpush
# script does the same thing
[ -t 0 ] || cat >/dev/null

[ -z "$GL_REPO" ] && die GL_REPO not set

targets=$(git config --get gitolite.mirror.simple)
[ -z "$targets" ] && exit 0

extra_args=$(git config --get gitolite.mirror.simple.extra-args)

for target in $targets; do
	# Support a REPO variable for wildcard mirrors
	gl_repo_escaped=$(echo $GL_REPO | sed 's/\//\\\//g')
	target=$(echo $target | sed -e "s/REPO/$gl_repo_escaped/g")

	# Do the mirror push
	git push --mirror $target $extra_args
done
